pipeline
{
agent any

parameters {
          string(name: 'TAG', defaultValue: '', description: 'Please enter tag name?')
}

triggers {
     cron (* * * * *)
}

 stages
 {
   stage('GIT Checkout')
   {
    steps
    {
     checkout scm
    }
   }

  stage('Build')
  {
   steps 
   {
    sh '/home/bish/Distros/apache-maven-3.6.1/bin/mvn install -Dbuild_no=${BUILD_NUMBER}'
  
   }
  }
  
 stage('Deployment')
  {
   steps
   {
     sh 'sshpass -p "bish" scp target/walkart.war bish@172.17.0.4:/home/bish/Distros/apache-tomcat-8.5.41/webapps'
     sh 'sshpass -p "bish" ssh bish@172.17.0.4 "JAVA_HOME=/home/bish/Distros/jdk1.8.0_211" "/home/bish/Distros/apache-tomcat-8.5.41/bin/startup.sh"'
   }
  }  

 }

}
